name: deploy_frontend
# Deploys when push is made from the frontend folder

on:
    push:
        branches: 
            - main
        paths:
          - 'frontend/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v4

    - name: azure login
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureresumefaizan --account-key ${{secrets.AZURE_STORAGE_ACCOUNT_KEY}} -d '$web' -s frontend/ --overwrite true
    
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azureresumefaizanshaikh" --name "azureresumefaizanshaikh" --resource-group "faizresume-rg"
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()